export const authSagaActions = {
    SEND_FORGOT_PWD: 'SEND_FORGOT_PWD',
    SIGNUP_USER: 'SIGNUP_USER',
    LOGIN_USER: 'LOGIN_USER',
    VERIFY_EMAIL: 'VERIFY_EMAIL',
    GET_PRODUCTS: 'GET_PRODUCTS',
    PLAN_PRODUCTS: 'PLAN_PRODUCTS',
    SELECT_PLAN_PRODUCTS:' SELECT_PLAN_PRODUCTS'
};
